# Generated by Django 2.2.4 on 2019-08-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingPlat', '0002_auto_20190823_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid',
            new_name='CallBid',
        ),
        migrations.RemoveField(
            model_name='winbid',
            name='tenderee',
        ),
    ]
