# Generated by Django 2.2.4 on 2019-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildingPlat', '0003_auto_20190823_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbid',
            name='purl',
            field=models.URLField(default='--', max_length=225, verbose_name='链接网址'),
        ),
        migrations.AlterField(
            model_name='winbid',
            name='purl',
            field=models.URLField(default='--', max_length=225, verbose_name='链接网址'),
        ),
    ]
